# Generated by Django 5.0.4 on 2024-04-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_maintenancier',
        ),
    ]
